name: "AWS CDK Destroy Workflow"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      WORKING-DIRECTORY:
        description: "The directory where CDK commands should be run"
        required: false
        default: "."  #root of the project
        type: string

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22.8.0'
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}
      - name: Bootstrap CDK (optional if already bootstrapped)
        run: npx cdk bootstrap
        working-directory: ${{ inputs.working-directory }}
      - name: CDK Destroy
        run: npx cdk destroy --all --force
        working-directory: ${{ inputs.working-directory }}