name: "AWS CDK Deploy Workflow"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      WORKING-DIRECTORY:
        description: "The directory where CDK commands should be run"
        required: false
        default: "."  #root of the project

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/aws-cdk-deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          WORKING-DIRECTORY: ${{ inputs.WORKING-DIRECTORY }}