name: "Terraform Apply"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
    inputs:
      WORKING-DIRECTORY:
        description: "The directory where Terraform commands should be run"
        required: false
        default: "."  #root of the project
        type: string
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - uses: actions/checkout@v4
      - run: terraform init
        working-directory: ${{ inputs.working-directory }}
      - run: terraform apply -auto-approve
        working-directory: ${{ inputs.working-directory }}